name: springboard-iogt
user: ubuntu
buildscript: sideloader/deploy.sh
postinstall: sideloader/postinstall.sh
pip: []
dependencies:
 - python-yaml
 - cmake
 - elasticsearch
 - libssl-dev
 - libffi-dev
